### ISSUE TITLE
score Management 개발

### ISSUE THREAD

**Issue by beginninggrace** [Modafi/NBC-admin-project#5]
~~- [ ]  : 필수/선택 과목에 따른 점수별 등급 기준 개발~~

~~- [ ]  :  과목별 시험 회차 및 점수를 등록~~

~~- [ ]  :  과목별 회차 점수를 수정~~

~~- [ ]  :  본인의 특정 과목의 회차별 등급을 조회~~

**Comment by Modafi** [comment]
동현님과 효일님이 이 개발하는 것으로 변경
@tangpoo 
@kudongku
